### ISSUE TITLE
pressing submit does nothing

### ISSUE THREAD

**Issue by hydazz** [bitswired/ai-chat-app#41]
running the container with the following command results in chats not working, the API key saves, and when I click submit it thinks, but does nothing:

```
docker run -p 8113:3000 \
  -e DATABASE_URL=file:./db.sqlite \
  -e NEXTAUTH_SECRET=secret \
  -e NEXTAUTH_URL=http://192.168.1.2:8113/ \
  -e ADMIN_EMAIL=admin@admin.com \
  -e ADMIN_PASSWORD=password \
  bitswired/ai-chat-app:single-user-latest
```

same behaviour on unraid and an M1 MacBook
should note it used to work.

possible related error:
```
prisma:error 
Invalid `prisma.user.findUniqueOrThrow()` invocation:


An operation failed because it depends on one or more records that were required but not found. Expected a record, found none.
```

full logs:
```
yarn run v1.22.19
$ /app/node_modules/.bin/prisma migrate deploy
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "db.sqlite" at "file:./db.sqlite"

SQLite database db.sqlite created at file:./db.sqlite

6 migrations found in prisma/migrations

Applying migration `20230302135639_init`
Applying migration `20230303145339_cascade_delete`
Applying migration `20230303183658_add_settings`
Applying migration `20230303235937_add_templates`
Applying migration `20230312154530_auth`
Applying migration `20230312205338_add_tenant_id`

The following migrations have been applied:

migrations/
  └─ 20230302135639_init/
    └─ migration.sql
  └─ 20230303145339_cascade_delete/
    └─ migration.sql
  └─ 20230303183658_add_settings/
    └─ migration.sql
  └─ 20230303235937_add_templates/
    └─ migration.sql
  └─ 20230312154530_auth/
    └─ migration.sql
  └─ 20230312205338_add_tenant_id/
    └─ migration.sql
      
All migrations have been successfully applied.
Done in 4.75s.
yarn run v1.22.19
$ next start
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
Warning: For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'yarn add sharp', and Next.js will use it automatically for Image Optimization.
Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
prisma:error 
Invalid `prisma.user.findUniqueOrThrow()` invocation:


An operation failed because it depends on one or more records that were required but not found. Expected a record, found none.
[next-auth][error][JWT_SESSION_ERROR] 
https://next-auth.js.org/errors#jwt_session_error No User found {
  message: 'No User found',
  stack: 'NotFoundError: No User found\n' +
    '    at /app/node_modules/@prisma/client/runtime/library.js:164:6701\n' +
    '    at async /app/node_modules/@prisma/client/runtime/library.js:164:6641\n' +
    '    at async Object.session (/app/.next/server/chunks/887.js:122:30)\n' +
    '    at async Object.session (/app/node_modules/next-auth/core/routes/session.js:56:26)\n' +
    '    at async AuthHandler (/app/node_modules/next-auth/core/index.js:158:27)\n' +
    '    at async NextAuthHandler (/app/node_modules/next-auth/next/index.js:24:19)\n' +
    '    at async /app/node_modules/next-auth/next/index.js:60:32\n' +
    '    at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:372:9)\n' +
    '    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:514:9)\n' +
    '    at async Object.fn (/app/node_modules/next/dist/server/next-server.js:828:35)',
  name: 'NotFoundError'
}
[Object: null prototype] {
  username: 'admin@admin.com',
  password: 'password',
  callbackUrl: '/',
  csrfToken: '3baf6d861c0b1c5ec1f7b98587874984b2ccf9409eb261b5f2696262ef38a825',
  json: 'true'
} true true
JDDDDDDDIIIIDDD
[Object: null prototype] {
  username: 'admin@admin.com',
  password: 'password',
  callbackUrl: '/',
  csrfToken: '12ddaa65f016860d5b00a21904d3b9d55d8ead83641375419328ce50f06d4a81',
  json: 'true'
} true true
JDDDDDDDIIIIDDD
```

**Comment by kysdaddy** [comment]
I am seeing the same thing, I installed a couple of weeks ago and love the app but today I get nothing. At first I assumed that I had fouled something up, but I am getting the same errors today.


An operation failed because it depends on one or more records that were required but not found. Expected a record, found none.
prisma:error 
Invalid `prisma.chat.findUniqueOrThrow()` invocation:


An operation failed because it depends on one or more records that were required but not found. Expected a record, found none.

any assistance is greatly appreciated. 

Chas

**Comment by kysdaddy** [comment]
My bad. My issue was 100% self-created operator malfunction.
It seems that when the chatgpt trial expires, AI chat has no way to notify you, it simply fails to connect..
Issue resolved by giving chatGPT a credit card.
